# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Stagecraft - Stagecraft is a Go-based CLI that orchestrates local-first development and scalable single-host to multi-host deployments for multi-service applications powered by Docker Compose.
#
# Copyright (C) 2025  Bartek Kus
#
# This program is free software licensed under the terms of the GNU AGPL v3 or later.
#
# See https://www.gnu.org/licenses/ for license details.
#
# golangci-lint configuration for Stagecraft
version: "2"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - .bin

linters:
  default: standard

  enable:
    - staticcheck   # Advanced Go static analysis
    - errcheck      # Check for unchecked errors
    - govet         # Go vet
    - ineffassign   # Detect ineffectual assignments
    - misspell      # Spelling checker
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Unused function parameters
    - gosec         # Security issues
    - gocritic      # Opinionated code analyzer
    - revive        # Fast, configurable linter

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        # - hugeParam   # optional: globally disable this check
    revive:
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: warning
        - name: package-comments
          severity: warning
    gosec:
      severity: medium
      confidence: medium

  exclusions:
    warn-unused: true
    paths:
      - vendor
      - test/e2e
      - ".*\\.pb\\.go$"
    rules:
      - path: _test\.go
        linters:
          - funlen
          - gocognit
      - text: "func main is too long"
        linters:
          - funlen

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      # this is the v2 place for the old gofmt.simplify setting
      simplify: true

    goimports:
      # this is where local-prefixes goes in v2
      local-prefixes:
        - stagecraft

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # leave other options (uniq-by-line, new, etc) at defaults for now
