# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Stagecraft - Stagecraft is a Go-based CLI that orchestrates local-first development and scalable single-host to multi-host deployments for multi-service applications powered by Docker Compose.
#
# Copyright (C) 2025  Bartek Kus
#
# This program is free software licensed under the terms of the GNU AGPL v3 or later.
#
# See https://www.gnu.org/licenses/ for license details.
#
# golangci-lint configuration for Stagecraft

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # Start from the standard set; override with enable/disable below if you like.
  default: standard

  enable:
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - govet
    - shadow
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic
    - revive

  # Add linter-specific settings here (replaces old top-level linters-settings).
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: stagecraft
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        # - hugeParam   # uncomment to globally disable this check if needed
    revive:
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: warning
        - name: package-comments
          severity: warning
    gosec:
      severity: medium
      confidence: medium

  # Replaces issues.exclude-*, issues.exclude-rules.
  exclusions:
    # Optional; warns if an exclusion is never matched.
    warn-unused: true

    # These replace issues.exclude-dirs and issues.exclude-files.
    paths:
      - vendor
      - test/e2e
      - ".*\\.pb\\.go$"

    # These replace issues.exclude-rules.
    rules:
      # Allow _test.go files to have longer functions/complexity.
      - path: _test\.go
        linters:
          - funlen
          - gocognit

      # Allow main functions to be longer.
      - text: "func main is too long"
        linters:
          - funlen

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # leave other options (uniq-by-line, new, etc) at defaults for now
