# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Stagecraft - Stagecraft is a Go-based CLI that orchestrates local-first development and scalable
# single-host to multi-host deployments for multi-service applications powered by Docker Compose.
#
# Copyright (C) 2025  Bartek Kus
#
# golangci-lint configuration for Stagecraft
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - staticcheck   # Advanced Go static analysis
    - errcheck      # Check for unchecked errors
    - gofmt         # Format check
    - goimports     # Import formatting
    - govet         # Go vet
    - shadow        # Detect variable shadowing (replacement for govet.check-shadowing)
    - ineffassign   # Detect ineffectual assignments
    - misspell      # Spelling checker
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Unused function parameters
    - gosec         # Security issues
    - gocritic      # Opinionated code analyzer
    - revive        # Fast, configurable linter

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: stagecraft
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport     # Sometimes needed for clarity
      - ifElseChain   # Can be more readable than switch in some cases
      # - hugeParam   # Uncomment to globally disable this check if it’s too noisy
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning
  gosec:
    severity: medium
    confidence: medium

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-dirs:
    - vendor
    - test/e2e   # E2E tests may have different patterns

  exclude-files:
    - ".*\\.pb\\.go$"  # Generated protobuf files (if any)

  exclude-rules:
    # Allow _test.go files to have longer functions and higher complexity
    - path: _test\.go
      linters:
        - funlen
        - gocognit

    # (Optional) Relax gosec for specific rules in tests
    - path: _test\.go
      linters:
        - gosec
      text: "G304"   # Potential file inclusion via variable in tests

    - path: _test\.go
      linters:
        - gosec
      text: "G306"   # Permissions 0600 or less in tests

    # Allow main functions to be longer
    - text: "func main is too long"
      linters:
        - funlen

