package xray

// Index matches the schema of index.json generated by the Rust XRAY binary.
type Index struct {
	SchemaVersion string         `json:"schemaVersion"`
	Root          string         `json:"root"`
	Target        string         `json:"target"`
	Stats         RepoStats      `json:"stats"`
	Files         []FileNode     `json:"files"`
	Languages     map[string]int `json:"languages"`
	TopDirs       map[string]int `json:"topDirs"`
	ModuleFiles   []string       `json:"moduleFiles"`
	Digest        string         `json:"digest"`
}

type RepoStats struct {
	FileCount int   `json:"fileCount"`
	TotalSize int64 `json:"totalSize"`
}

type FileNode struct {
	Path       string `json:"path"`
	Size       int64  `json:"size"`
	Hash       string `json:"hash"`
	Lang       string `json:"lang"`
	LOC        int    `json:"loc"`
	Complexity int    `json:"complexity"`
}
